### ISSUE TITLE
What does command "shape" mean in polstm.q?

### ISSUE THREAD

**Issue by liutongwei** [krish240574/lstmq#1]
Hi, I'm using KDB+ 3.5 and I find there is a command in line#89:

`H:(shape H)#K;`

It dose not work and report an error with "shape".

So I wonder whether the command shape can only be used in KDB+ with version above 4.0 or is there any code to calculate number of rows and columns of a table?

**Comment by krish240574** [comment]
So sorry, I had defined shape as my own function, for 2d arrays with
constant size -
k)shape:{(#x),(#x[0])}

Will update the code, thank you for pointing that out, I usually have that
in my pre-load file, inside q.q

Kumar

**Comment by liutongwei** [comment]
Thanks for your reply. It now works.

**Comment by krish240574** [comment]
Most welcome. Thanks again.
